version: '2.3'
services:
    mendixapp:
        image: mendix/mendix-buildpack:v3.2.0
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost']
            interval: 15s
            retries: 2
            start_period: 10s
            timeout: 3s
        environment:
            ADMIN_PASSWORD: Password1!
            #DATABASE_ENDPOINT: mysql://mendix:mendix@db:3306/mendix
            MXRUNTIME_DatabaseType: MySql
            MXRUNTIME_DatabaseUserName: mendix
            MXRUNTIME_DatabasePassword: mendix
            MXRUNTIME_DatabaseHost: db:3306
            MXRUNTIME_DatabaseName: mendix
        ports:
            - 8080:8080
        links:
            - db
        mem_limit: 500mb
        
    db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=mendix
            - MYSQL_PASSWORD=mendix
            - MYSQL_DATABASE=mendix
            - MYSQL_ROOT_PASSWORD=root
        ports:
        - 3306:3306
        mem_limit: 300mb
